### ISSUE TITLE
General review

### ISSUE THREAD

**Issue by andresberrios** [andresberrios/statemirror#5]
State Track Plugin

- General concerns
  - Performance
    - JSON serializing on the plugin
    - Making transaction processing take longer and hit CPU time limit
      - Only for transactions sent directly to this node?
      - Does it affect validated transactions/blocks received from the network?
  - Forks
    - How to induce and test recovery
  - Consensus
    - Exceptions
    - Other potential disruptions
  - Socket communications
    - Sending messages right now blocks until they are received (PUSH socket)
    - This is useful in case receiver goes down, since nodeos will wait for it to come back up
      - Instead of maintaining a local in-memory queue of messages that can build up too much if it carries on
    - Lost messages
      - When receiver pulls a message from the socket but then crashes
        - Implement message acknowledgement signal?
        - Implement an intermediate receiver that only manages the queue?
        - Implement a very safe received-messages queue in receiver to recover from if it crashes?
- Chainbase
  - Differences in exception handling between emit functions
    - Chain
      [Link](https://github.com/EOSIO/eos/blob/master/libraries/chain/controller.cpp#L223)
    - Chainbase Fork
      [Link](https://github.com/EOSIO/chainbase/compare/master...mmcs85:master#diff-298563b6c76ef92100c2ea27c06cb08bR70)
  - This line seems to have been just removed without a purpose
    [Link](https://github.com/EOSIO/chainbase/compare/master...mmcs85:master#diff-298563b6c76ef92100c2ea27c06cb08bL502)
- Plugin
  - General code review
- Receiver
  - Remove undoer
  - Add Readme

**Comment by mmcs85** [comment]
1 - JSON serialization takes time on tx execution if handled directly.
  1.a) first solution is to delegate to the receiver side for later to parse it. 
         Upside is that serialization can be delayed until is needed.
         Downside is that you need to fetch abi for each op to be able to parse it.
  1.b) create a temporary queue that serializes JSON after tx is done executing.

2 - (chainbase)
2.a) emit function on chainbase is using a std::function instead of a signal. so it handles different exceptions.
2.b) the line is not removed is added later
_indices.erase( itr );

**Comment by andresberrios** [comment]
Current pending changes

- [ ] Signals implementation
- [ ] Bring back line that was removed (`stack` function)
- [ ] Exception handling in `emit` function should be the same as in Chain library
- [ ] Check for refactoring opportunities in plugin code
- [ ] Add more info to Readme

**Comment by mmcs85** [comment]
fixed some of the issues
